Fix WGSL shader compile error: redefinition of 'sky'
WGSL doesn't allow shadowing let bindings (let sky = mix(sky, ...)) and
'sky' also collides with the uniform struct name. Renamed the locals to
sky_horizon and sky_final.

Also removed the unused Mat3 import from fly_camera.rs (it's used via
the fully-qualified glam::Mat3 path in into_transform).